# Copyright (c) 2022 OpenFaaS Ltd
name: 'Setup the actuated-ssh-gateway'
description: 'Setup the actuated-ssh-gateway'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  gatewayaddr:
    description: 'The gateway hostname address or IP address.'
    required: true
  secure:
    description: 'Whether to use TLS.'
    required: true
    default: true
runs:
    using: 'composite'
    steps:
      - name: Download the ssh-gateway client
        shell: bash
        id: download
        run: |
          curl -s -S -L https://github.com/alexellis/gha-connect-client/releases/download/v0.0.1/gha-connect -o /tmp/gha-connect
          chmod +x /tmp/gha-connect
          sudo mv /tmp/gha-connect /usr/local/bin/
      - name: Where am i?
        shell: bash
        id: add_geolocation_script
        run: |
          echo "#!/bin/bash" | sudo tee -a /usr/local/bin/whereami
          echo "curl -s http://ip-api.com/json|jq" | sudo tee -a /usr/local/bin/whereami
          sudo chmod +x /usr/local/bin/whereami
      - name: Run the client in the background
        shell: bash
        id: connectbg
        env:
          SECURE: ${{ inputs.secure }}
          SSH_GATEWAY_ADDR: ${{ inputs.gatewayaddr }}
        run: |
          gha-connect -secure=${SECURE} -ip ${SSH_GATEWAY_ADDR} &
