# Copyright (c) 2022 OpenFaaS Ltd
name: 'Setup the actuated-ssh-gateway'
description: 'Setup the actuated-ssh-gateway'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  gateway:
    description: 'The gateway hostname address or IP address.'
    required: false
    default: ""
runs:
    using: 'composite'
    steps:
      - name: Download the ssh-gateway client
        shell: bash
        id: download
        run: |
          if [ "$(uname -m)" = "aarch64" ]
          then
            curl -s -S -L https://github.com/alexellis/gha-connect-client/releases/download/v0.0.2/gha-connect-arm64 -o /tmp/gha-connect
          else
            curl -s -S -L https://github.com/alexellis/gha-connect-client/releases/download/v0.0.2/gha-connect -o /tmp/gha-connect
          fi

          chmod +x /tmp/gha-connect
          sudo mv /tmp/gha-connect /usr/local/bin/
      - name: Where am i?
        shell: bash
        id: add_geolocation_script
        run: |
          echo "#!/bin/bash" | sudo tee -a /usr/local/bin/whereami
          echo "curl -s http://ip-api.com/json|jq" | sudo tee -a /usr/local/bin/whereami
          sudo chmod +x /usr/local/bin/whereami
      - name: Run the client in the background
        shell: bash
        id: connectbg
        env:
          GATEWAY: ${{ inputs.gateway }}
        run: |
          gha-connect -url ${GATEWAY:-""} &
